Repository GCUCoders/Tech-Club-Site, pull requests merged in 2021-11, with the labels that each got.

#14 added color scheme
  documentation/color-scheme-hex-codes.txt
  documentation/color-scheme.png
  documentation/placeholder.txt
Labels: frontend

#15 Navbar w/logo above
  contact.html
  css/style.css
  navbarssssssss.html
Labels: frontend

#21 added preexisting documentation to the repo
  documentation/colorscheme/color-scheme-hex-codes.txt
  documentation/colorscheme/color-scheme.png
  documentation/sitemap/sitemap.png
  documentation/wireframes/1about_wireframe.png
  documentation/wireframes/2mission_wireframe.png
  documentation/wireframes/3leadership_wireframe.png
  documentation/wireframes/4contact_wireframe.png
  documentation/wireframes/committees_wireframe.png
  documentation/wireframes/home_wireframe.png
  documentation/wireframes/merch_list_wireframe.png
  documentation/wireframes/merch_product_wireframe.png
  documentation/wireframes/navbar_wireframe.png
Labels: documentation, enhancement

#32 Add files via upload
  about_us.html
Labels: frontend

#33 Updated CSS(I know, finally)
  .gitignore
  about.html
  about_us.html
  committee.html
  css/about-style.css
  css/about_us-style.css
  css/committee-style.css
  css/contact-style.css
  css/merch-style.css
  css/navbar-style.css
  css/projects-style.css
  css/style (2).css
  merch.html
  navbar.html
  projects.html
Labels: enhancement, frontend

#35 Calendar
  calendar.html
  css/calendar-style.css
Labels: good first issue

#38 Added: committee.js, committee.css, committee.html. Added images: img…
  committee.html
  css/committee-style.css
  images/cyber_img.png
  images/img1.png
  js/committee.js
  navbar.html
Labels: frontend
